version: "3.8"
x-variaveis:
  &variaveis
    N8N_ENCRYPTION_KEY: noJbC3oLKzSGXEyRNtV0DoiQmK5zBG83
    N8N_HOST: n8n.seudominio.com.br
    N8N_EDITOR_BASE_URL: https://n8n.seudominio.com.br/
    N8N_PROTOCOL: https
    NODE_ENV: production
    WEBHOOK_URL: https://webhook.seudominio.com.br/
    EXECUTIONS_MODE: queue
    QUEUE_BULL_REDIS_HOST: redis
    QUEUE_BULL_REDIS_PORT: 6379
    QUEUE_BULL_REDIS_DB: 2
    NODE_FUNCTION_ALLOW_EXTERNAL: moment,lodash,moment-with-locales
    EXECUTIONS_DATA_PRUNE: "true"
    EXECUTIONS_DATA_MAX_AGE: 336
    N8N_COMMUNITY_PACKAGES_ENABLED: "true"
    N8N_EMAIL_MODE: smtp
    N8N_SMTP_HOST: stmp.host.com
    N8N_SMTP_USER: user@user.com
    N8N_SMTP_PASS: senhadoemailousmtp
    N8N_SMTP_SENDER: N8N <n8n@seudominio.com>
    N8N_SMTP_PORT: 465 # 587 | 25 | 993
    N8N_REINSTALL_MISSING_PACKAGES: "true"
    DB_TYPE: postgresdb
    DB_POSTGRESDB_PORT: 5432
    DB_POSTGRESDB_HOST: postgres # Endereço da database
    DB_POSTGRESDB_DATABASE: n8n
    DB_POSTGRESDB_USER: postgres
    DB_POSTGRESDB_PASSWORD: sennhadopostgres

services:
  n8n_editor:
    image: n8nio/n8n:latest
    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      replicas: 1
    placement:
      constraints:
        - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(`n8n.seudominio.com.br`)
        - traefik.http.routers.n8n_editor.service=n8n_editor
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.tls.certresolver=le
        - traefik.http.routers.n8n_editor.tls=true
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
    networks:
      - traefik_public
      - app_network
    volumes:
      - /root/apps/n8n/n8n-nodes:/home/node/.n8n/nodes

  n8n_webhook:
    image: n8nio/n8n:latest
    command: webhook
    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      replicas: 1
    placement:
      constraints:
        - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_webhook.rule=Host(`webhook.groufy.com.br`)
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.tls.certresolver=le
        - traefik.http.routers.n8n_webhook.tls=true
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
    networks:
      - traefik_public
      - app_network
    volumes:
      - /root/apps/n8n/n8n-nodes:/home/node/.n8n/nodes
  n8n_worker:
    image: n8nio/n8n:latest
    command: worker --concurrency=10
    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      replicas: 1
    placement:
      constraints:
        - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      - traefik_public
      - app_network
    volumes:
      - /root/apps/n8n/n8n-nodes:/home/node/.n8n/nodes

volumes:
  n8n-custom-nodes:

networks:
  traefik_public:
    external: true
  app_network:
    external: true
